// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nkkauogbkgkjgxlrvfbe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ra2F1b2dia2dramd4bHJ2ZmJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NzQ1MDEsImV4cCI6MjA3MTQ1MDUwMX0.CChwm8L91UBZJQVajX7fDx3ZssYqj9JKPY5OuHDJBvs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});